version: '3'
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    ports:
     - "4000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-data
    restart: always
    volumes: 
     - db-data:/var/lib/postgresql/data/

  # aws-storage:
  #   image: aws-storage
  #   build: 
  #     context: ./aws-storage
  #     dockerfile: Dockerfile.prod
  #   container_name: video-storage
  #   ports:
  #    - "4001:80"
  #   environment:
  #    - PORT=80
  #   restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.prod
    container_name: video-streaming
    ports: 
     - "4002:80"
    environment:
     - PORT=80
     - VIDEO_STORAGE_HOST=video-storage
     - VIDEO_STORAGE_PORT=80
     - DATABASE_URL=postgres://postgres:postgres@db:5432/db-data?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
    restart: "no"
    depends_on:
     - db
    
volumes:
  db-data:
    driver: local